[package]
name = "testnet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[package.metadata.cargo-udeps.ignore]
normal = [
  # Used for diagrams in docs
  "aquamarine",
]

[dependencies]
reth.workspace = true
reth-node-builder.workspace = true
alloy-chains.workspace = true
sol-bindings = { workspace = true, features = ["testnet"] }

blsful.workspace = true
consensus.workspace = true
angstrom-types.workspace = true
angstrom-utils.workspace = true
angstrom-network.workspace = true
angstrom-eth.workspace = true
angstrom-rpc.workspace = true
angstrom.workspace = true
order-pool.workspace = true
validation.workspace = true

reth-network-api.workspace = true
reth-network-peers.workspace = true
reth-codecs.workspace = true
reth-tasks.workspace = true
reth-rpc-types.workspace = true
reth-eth-wire.workspace = true
futures.workspace = true
jsonrpsee.workspace = true
alloy-rlp.workspace = true

alloy-primitives.workspace = true
alloy-sol-types.workspace = true

reth-node-ethereum.workspace = true
reth-revm.workspace = true
reth-blockchain-tree = { git = "https://github.com/paradigmxyz/reth", version = "1.0.0", tag = "v1.0.0" }
reth-beacon-consensus = { git = "https://github.com/paradigmxyz/reth", version = "1.0.0", tag = "v1.0.0" }
# reth-net-common = { git = "https://github.com/paradigmxyz/reth", version = "1.0.0" ,tag =  "v1.0.0" }
reth-tokio-util = { git = "https://github.com/paradigmxyz/reth", version = "1.0.0", tag = "v1.0.0" }
reth-dns-discovery = { git = "https://github.com/paradigmxyz/reth", version = "1.0.0", tag = "v1.0.0" }
reth-ecies = { git = "https://github.com/paradigmxyz/reth", version = "1.0.0", tag = "v1.0.0" }
alloy = { version = "0.1.3", features = [
  "full",
  "node-bindings",
  "rpc-types-debug",
  "rpc-types-trace",
  "json-rpc",
  "rpc-client",
  "signer-aws",
  "signer-keystore",
  "signer-ledger",
  "signer-mnemonic",
  "signer-trezor",
  "signer-yubihsm",
] }

alloy-provider = "0.1.3"
alloy-transport = "0.1.3"
alloy-transport-ws = "0.1.3"
alloy-pubsub.workspace = true
alloy-node-bindings.workspace = true
alloy-rpc-types-eth.workspace = true

# reth
reth-discv4 = { git = "https://github.com/paradigmxyz/reth", version = "1.0.0", tag = "v1.0.0", features = [
  "test-utils",
] }
# reth-interfaces = { workspace = true, features = ["test-utils"] }
reth-primitives = { workspace = true, features = ["test-utils"] }

# we need to enable the test-utils feature in our own crate to use utils in
# integration tests
reth-network = { workspace = true, features = ["test-utils"] }
reth-metrics.workspace = true

tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

tokio.workspace = true
tokio-stream.workspace = true
reth-provider = { workspace = true, features = ["test-utils"] }
reth-tracing.workspace = true
reth-transaction-pool = { workspace = true, features = ["test-utils"] }
reth-db.workspace = true


enr = { workspace = true, features = ["serde", "rust-secp256k1"] }
rand.workspace = true
secp256k1.workspace = true

# misc
serial_test.workspace = true
tempfile.workspace = true

parking_lot.workspace = true
clap = { version = "4.5.4", features = ["derive"] }
eyre = "0.6.12"

[target.'cfg(unix)'.dependencies]
tikv-jemallocator = { version = "0.5.0", optional = true }


[features]
default = ["jemalloc"]
jemalloc = ["dep:tikv-jemallocator"]
jemalloc-prof = ["jemalloc", "tikv-jemallocator?/profiling"]


[[bin]]
name = "testnet"
path = "src/main.rs"
