[package]
name = "matching-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
angstrom-utils.workspace = true
alloy-primitives.workspace = true
malachite = "0.4.0"
malachite-q = "0.4.0"
