[package]
name = "consensus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio.workspace = true
futures.workspace = true
thiserror.workspace = true
reth-network.workspace = true
reth-primitives.workspace = true
ethers-providers.workspace = true
ethers-signers.workspace = true
ethers-middleware.workspace = true
ethers-core.workspace = true
tracing.workspace = true
reth-rpc-builder.workspace = true
async-trait.workspace = true
tokio-stream.workspace = true
serde.workspace = true
anyhow.workspace = true
url.workspace = true
reth-db.workspace = true
reth-provider.workspace = true
reth-tracing.workspace = true
serde_json.workspace = true
hex-literal.workspace = true
revm-primitives.workspace = true
reth-rlp.workspace = true
rayon.workspace = true

guard-types.workspace = true
# guard-provider.workspace = true
sim.workspace = true
