[profile.default]
solc           = "0.8.24"
bytecode_hash  = "none"
optimizer_runs = 1_000_000
verbosity      = 3
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/" }]
evm_version    = "cancun"

ignored_error_codes = [
  2394, # Transient storage warning
  3860, # Initcode size too large
  5574  # Contract size too large
]

remappings = [
  "solady/src/=lib/solady/src/",
  "v4-core/src/=lib/v4-core/src/"
]

[profile.diff-fuzz]
match_path = "test/diff-fuzz/*"
ffi        = true
chain-id   = 1

[profile.ci]
fuzz-runs = 10_000
