[profile.default]
solc           = "0.8.26"
bytecode_hash  = "none"
viaIR = false
optimizer_runs = 1_000_000
verbosity      = 3
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/" }]
evm_version    = "cancun"

ignored_error_codes = [
  2394, # Transient storage warning
  3860, # Initcode size too large
  5574  # Contract size too large
]

remappings = [
  "solady/src/=lib/solady/src/",
  "v4-core/src/=lib/v4-core/src/",
  "solmate/=lib/solmate/"
]

[profile.dev-deopt]
optimizer = false
