[package]
name = "contract_test"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
angstrom-types.workspace = true
testing-tools.workspace = true
tokio.workspace = true
uniswap_v3_math.workspace = true
alloy.workspace = true
pade.workspace = true
pade-macro.workspace = true
eyre.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true